<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sockseek.Api</AssemblyName>
    <RootNamespace>Sockseek.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="10.0.9" />
    <ProjectReference Include="..\Sockseek.Core\Sockseek.Core.csproj" />
  </ItemGroup>

</Project>
