<Project>
  <PropertyGroup>
    <VersionPrefix>3.0.5</VersionPrefix>
    <VersionSuffix></VersionSuffix>

    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <!-- Redirect the lock file to the ignored 'obj' folder during manual publishes -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' Or '$(SelfContained)' == 'true' Or '$(PublishSingleFile)' == 'true' Or '$(PublishTrimmed)' == 'true'">
    <NuGetLockFilePath>obj/packages.publish.lock.json</NuGetLockFilePath>
  </PropertyGroup>
</Project>