<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.11.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Sockseek.Api/Sockseek.Api.csproj" />
    <ProjectReference Include="../Sockseek.Core/Sockseek.Core.csproj" />
    <ProjectReference Include="../Sockseek.Cli/Sockseek.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Sockseek.Core.Tests/TestClients/MockSoulseekClient.cs" Link="TestClients/MockSoulseekClient.cs" />
    <Compile Include="../Sockseek.Core.Tests/TestClients/MockSoulseekClientNotImpl.cs" Link="TestClients/MockSoulseekClientNotImpl.cs" />
  </ItemGroup>

</Project>
