blank_issues_enabled: false

contact_links:
  - name: Discussion & Support
    url: https://github.com/fiso64/sockseek/discussions/categories/q-a
    about: Please ask questions here rather than using issues.