// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sockseek.Persistence;

#nullable disable

namespace Sockseek.Persistence.Migrations
{
    [DbContext(typeof(SockseekDbContext))]
    partial class SockseekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Sockseek.Persistence.Entities.ChatConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayUsername")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_username");

                    b.Property<long>("LastMessageSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_message_sequence");

                    b.Property<long>("LastReadSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_read_sequence");

                    b.Property<string>("LocalAccountKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_account_key");

                    b.Property<string>("PeerKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("peer_key");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LocalAccountKey", "PeerKey")
                        .IsUnique();

                    b.HasIndex("LocalAccountKey", "LastMessageSequence", "Id");

                    b.ToTable("chat_conversations", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_conversations_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_chat_conversations_sequences", "last_read_sequence >= 0 AND last_message_sequence >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("DisplaySender")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_sender");

                    b.Property<string>("DisplayTarget")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_target");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("LocalAccountKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_account_key");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int?>("ProtocolMessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("protocol_message_id");

                    b.Property<long?>("ProtocolTimestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("protocol_timestamp");

                    b.Property<long>("RecordedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("SendState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_state");

                    b.Property<string>("SenderKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_key");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_key");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_kind");

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("LocalAccountKey", "SendState");

                    b.HasIndex("LocalAccountKey", "TargetId", "Sequence", "Id");

                    b.HasIndex("LocalAccountKey", "TargetKind", "TargetKey", "ProtocolMessageId", "ProtocolTimestamp")
                        .IsUnique()
                        .HasFilter("protocol_message_id IS NOT NULL");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.ChatRoomSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("room_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("room_kind");

                    b.Property<long>("LastMessageSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_message_sequence");

                    b.Property<long>("LastReadSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_read_sequence");

                    b.Property<string>("LocalAccountKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_account_key");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("room_key");

                    b.Property<bool>("RuntimeDesired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime_desired");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LocalAccountKey", "RoomKey")
                        .IsUnique();

                    b.HasIndex("LocalAccountKey", "RuntimeDesired");

                    b.HasIndex("LocalAccountKey", "LastMessageSequence", "Id");

                    b.ToTable("chat_room_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_room_subscriptions_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_chat_room_subscriptions_sequences", "last_read_sequence >= 0 AND last_message_sequence >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.ChatSequenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_id");

                    b.Property<long>("LastMessageSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_message_sequence");

                    b.Property<long>("LastNotificationSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_notification_sequence");

                    b.HasKey("Id");

                    b.ToTable("chat_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_sequences_singleton", "sequence_id = 1");

                            t.HasCheckConstraint("ck_chat_sequences_values", "last_message_sequence >= 0 AND last_notification_sequence >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.InputArtifactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("ExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at_utc");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc", "Id");

                    b.ToTable("input_artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_input_artifacts_length", "length >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.InputArtifactPinEntity", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_id");

                    b.Property<string>("OwnerKind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.HasKey("ArtifactId", "OwnerKind", "OwnerId");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("input_artifact_pins");
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActivityPhase")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT")
                        .HasColumnName("activity_phase");

                    b.Property<long?>("ActivityUntilUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activity_until_utc");

                    b.Property<string>("CancellationSource")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_source");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("DisplayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_id");

                    b.Property<string>("FailureDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_detail");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_message");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ItemName")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<Guid>("LastRuntimeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_runtime_id");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sequence");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_job_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<int>("PayloadSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payload_schema_version");

                    b.Property<string>("QueryText")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("query_text");

                    b.Property<string>("SemanticRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("semantic_role");

                    b.Property<Guid?>("ResultJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_job_id");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("SkipReason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT")
                        .HasColumnName("skip_reason");

                    b.Property<Guid?>("SourceJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_job_id");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("submission_id");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("TerminalOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_outcome");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("ParentJobId");

                    b.HasIndex("ResultJobId");

                    b.HasIndex("SourceJobId");

                    b.HasIndex("SubmissionId", "DisplayId", "Id");

                    b.HasIndex("CreatedAtUtc", "Id");

                    b.HasIndex("LastRuntimeId", "LifecycleState");

                    b.HasIndex("LifecycleState", "CompletedAtUtc");

                    b.HasIndex("ParentJobId", "DisplayId", "Id");

                    b.HasIndex("WorkflowId", "CreatedAtUtc", "Id");

                    b.HasIndex("WorkflowId", "DisplayId", "Id");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_display_id", "display_id > 0");

                            t.HasCheckConstraint("ck_jobs_last_sequence", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_jobs_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_jobs_terminal_time", "(lifecycle_state = 'Terminal' AND completed_at_utc IS NOT NULL) OR (lifecycle_state <> 'Terminal' AND completed_at_utc IS NULL)");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("LocalAccountKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_account_key");

                    b.Property<long?>("ReadAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("read_at_utc");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_message_id");

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("LocalAccountKey", "SourceMessageId", "Kind")
                        .IsUnique();

                    b.HasIndex("LocalAccountKey", "ReadAtUtc", "Sequence", "Id");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.PeerRestrictionOverrideEntity", b =>
                {
                    b.Property<string>("RestrictionKind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("restriction_kind");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY")
                        .HasColumnName("username");

                    b.Property<string>("OverrideState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("override_state");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("RestrictionKind", "Username");

                    b.HasIndex("Username", "RestrictionKind");

                    b.ToTable("peer_restriction_overrides");
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.RuntimeSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ShutdownKind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("shutdown_kind");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<long?>("StoppedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stopped_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("runtime_sessions", (string)null);
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.SearchJobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_complete");

                    b.Property<long>("LockedFileCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("locked_file_count");

                    b.Property<long>("ObservedPeerCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observed_peer_count");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("query");

                    b.Property<long>("ResultCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result_count");

                    b.Property<string>("ResultPersistenceState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("result_persistence_state");

                    b.Property<long?>("ResultsPrunedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("results_pruned_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.HasKey("JobId");

                    b.HasIndex("ResultPersistenceState", "CompletedAtUtc");

                    b.ToTable("search_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_search_jobs_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.SearchResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes_json");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bit_depth");

                    b.Property<int?>("BitRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bit_rate");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<bool?>("HasFreeUploadSlot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_free_upload_slot");

                    b.Property<long>("ObservedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("observed_at_utc");

                    b.Property<int?>("QueueLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_length");

                    b.Property<string>("RemoteFilename")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_filename");

                    b.Property<int>("ResponseFileCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_file_count");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sample_rate");

                    b.Property<Guid>("SearchJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_job_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<int?>("UploadSpeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upload_speed");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("SearchJobId", "Sequence")
                        .IsUnique();

                    b.HasIndex("SearchJobId", "Username");

                    b.HasIndex("SearchJobId", "Username", "RemoteFilename", "Visibility")
                        .IsUnique();

                    b.ToTable("search_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_search_results_revision", "revision > 0");

                            t.HasCheckConstraint("ck_search_results_sequence", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.SubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("ArtifactId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_id");

                    b.Property<string>("CommitFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("commit_fingerprint");

                    b.Property<string>("CommitReceiptJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("commit_receipt_json");

                    b.Property<Guid?>("PreviewId")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_id");

                    b.Property<Guid?>("RerunOfSubmissionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("rerun_of_submission_id");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("SpecificationSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("specification_schema_version");

                    b.Property<string>("SpecificationJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("specification_json");

                    b.Property<long>("SubmittedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("submitted_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAtUtc");

                    b.HasIndex("RerunOfSubmissionId");

                    b.HasIndex("SubmittedAtUtc", "Id");

                    b.ToTable("submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissions_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_submissions_specification_schema", "specification_schema_version > 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferAccountingCheckpointEntity", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("attempt_id");

                    b.Property<long>("CumulativeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cumulative_bytes");

                    b.Property<long>("LastObservedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transfer_id");

                    b.HasKey("AttemptId");

                    b.HasIndex("TransferId");

                    b.ToTable("transfer_accounting_checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfer_accounting_checkpoint_bytes", "cumulative_bytes >= 0");
                            t.HasCheckConstraint("ck_transfer_accounting_checkpoint_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferAccountingStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_id");

                    b.Property<long>("CompleteFromUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("complete_from_utc");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("transfer_accounting_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfer_accounting_state_coverage", "complete_from_utc >= 0");
                            t.HasCheckConstraint("ck_transfer_accounting_state_singleton", "state_id = 1");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_number");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_message");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("LastRuntimeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_runtime_id");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sequence");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_path");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<string>("SourceUsername")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_username");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id");

                    b.HasIndex("LastRuntimeId", "CompletedAtUtc");

                    b.HasIndex("TransferId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("TransferId", "StartedAtUtc");

                    b.ToTable("transfer_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfer_attempts_last_sequence", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_transfer_attempts_number", "attempt_number > 0");

                            t.HasCheckConstraint("ck_transfer_attempts_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferByteBucketEntity", b =>
                {
                    b.Property<long>("BucketStartUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bucket_start_utc");

                    b.Property<string>("Direction")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.HasKey("BucketStartUtc", "Direction", "Username");

                    b.HasIndex("Direction", "BucketStartUtc");
                    b.HasIndex("Username", "BucketStartUtc");

                    b.ToTable("transfer_byte_buckets", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfer_byte_bucket_bytes", "bytes >= 0");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<long?>("ArchivedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived_at_utc");

                    b.Property<long?>("BytesPerSecond")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_per_second");

                    b.Property<string>("CancellationSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_source");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_message");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FileAttributesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_attributes_json");

                    b.Property<int?>("FileBitDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_bit_depth");

                    b.Property<int?>("FileBitRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_bit_rate");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_extension");

                    b.Property<int?>("FileLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_length");

                    b.Property<string>("FileName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<int?>("FileSampleRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_sample_rate");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("GroupRef")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_ref");

                    b.Property<string>("GroupDisplayPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_display_path");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<long?>("LastProgressAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_progress_at_utc");

                    b.Property<Guid>("LastRuntimeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_runtime_id");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sequence");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<string>("RemotePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_path");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("TerminalOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_outcome");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_bytes");

                    b.Property<long>("TransferredBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transferred_bytes");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("ArchivedAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("JobId");

                    b.HasIndex("LastRuntimeId", "TerminalOutcome");

                    b.HasIndex("Direction", "StartedAtUtc", "Id");

                    b.HasIndex("Direction", "State", "CreatedAtUtc");

                    b.HasIndex("Direction", "TerminalOutcome", "CompletedAtUtc");

                    b.HasIndex("WorkflowId", "CreatedAtUtc", "Id");

                    b.HasIndex("Username", "Direction", "StartedAtUtc", "Id");

                    b.ToTable("transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_transfers_bytes", "total_bytes >= 0 AND transferred_bytes >= 0");

                            t.HasCheckConstraint("ck_transfers_last_sequence", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_transfers_revision", "revision >= 0");

                            t.HasCheckConstraint("ck_transfers_terminal_time", "(terminal_outcome = 'None' AND completed_at_utc IS NULL) OR (terminal_outcome <> 'None' AND completed_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.JobEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.RuntimeSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("LastRuntimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sockseek.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sockseek.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("ResultJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sockseek.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceJobId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.InputArtifactPinEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.InputArtifactEntity", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.ChatMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.SearchJobEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.JobEntity", null)
                        .WithOne()
                        .HasForeignKey("Sockseek.Persistence.Entities.SearchJobEntity", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.SearchResultEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.SearchJobEntity", null)
                        .WithMany()
                        .HasForeignKey("SearchJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.SubmissionEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.SubmissionEntity", null)
                        .WithMany()
                        .HasForeignKey("RerunOfSubmissionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferAttemptEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.RuntimeSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("LastRuntimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sockseek.Persistence.Entities.TransferEntity", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferAccountingCheckpointEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.TransferEntity", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sockseek.Persistence.Entities.TransferEntity", b =>
                {
                    b.HasOne("Sockseek.Persistence.Entities.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sockseek.Persistence.Entities.RuntimeSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("LastRuntimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
