<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Sockseek.Core</AssemblyName>
    <RootNamespace>Sockseek.Core</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="AngleSharp" Version="1.7.1" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.75.0.4207" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="SmallestCSVParser" Version="1.2.0" />
    <PackageReference Include="Soulseek" Version="10.0.2" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.4.2" />
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.4.2" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.1" />
  </ItemGroup>

</Project>
