name: sldl_ui
description: A GUI wrapper for slsk-batchdl — the smart Soulseek downloader.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
